<?php

/*
 * Implements hook_permission()
 */
function quiz_properties_access_permission(){
	$permissions = array(
		'edit quiz properties' => array(
			'title' => t('Edit a quiz\'s properties'),
			'description' => t('Permission to edit a quiz\'s properties on its node edit form.'),
		), 
	);
	return $permissions;
}

/*
 * Implements hook_form_alter()
 * Hide properties section from quiz forms as specified by a permission
 */
function quiz_properties_access_form_alter(&$form, &$form_state, $form_id){
	//performance: check that the form is the quiz edit form, before calling a global variable and loading an object
	if($form_id == "quiz_node_form"){
		global $user;
		$uid = $user->uid;
		if(!user_access('edit quiz properties') && $uid != 1){
			$form["resultoptions"]["#type"]="hidden";
			$form["quiz_availability"]["#type"]="hidden";
			$form["taking"]["#type"]="hidden";
			$form["summaryoptions"]["#type"]="hidden";
			$form["remember_settings"]["#type"]="hidden";
			$form["remember_global"]["#type"]="hidden";			
		}
	}
}
